[package]
name = "pwm-fan-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
clap = { version = "3.2.14", features = ["derive"] }
once_cell = "1.13.0"
ctrlc = "3.2.2"
itertools = "0.10.3"
